"""added user-cafe relationship

Revision ID: 0ae1115f2bfb
Revises: 05a5645bf675
Create Date: 2021-08-15 10:34:43.412006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae1115f2bfb'
down_revision = '05a5645bf675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafe', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cafe', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cafe', type_='foreignkey')
    op.drop_column('cafe', 'user_id')
    # ### end Alembic commands ###
