"""Added create date/update date to cafe

Revision ID: 1a96f4545515
Revises: a7b67c3cc253
Create Date: 2021-08-23 19:24:21.110427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a96f4545515'
down_revision = 'a7b67c3cc253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafe', sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('cafe', sa.Column('time_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafe', 'time_updated')
    op.drop_column('cafe', 'time_created')
    # ### end Alembic commands ###
