"""Added cafe thumbnail

Revision ID: a7b67c3cc253
Revises: b75528c6f4a4
Create Date: 2021-08-22 16:14:28.670176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b67c3cc253'
down_revision = 'b75528c6f4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafe', sa.Column('thumbnail', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafe', 'thumbnail')
    # ### end Alembic commands ###
